### PR TITLE
#107: Proxy Support

### PR DESCRIPTION
**Pull request by dowlingw**
Adds support for proxy server and configuration.

Can confirm this approach works using the corporate proxy at my employer.
Other attempts using nodes inbuilt `http`/`https` modules did not work.

Just going to park this here over the weekend to get some feedback from the maintainers.

I'm not sure what testing makes sense, as this quickly gets into testing inside `request` module.

### CODE REVIEW

**Comment by JamesMessinger** [comment]
Thanks for the PR!  I'll review it soon and get it merged 👍

**Comment by JamesMessinger** [comment]
`request` is a great package for Node.js apps, but `json-schema-ref-parser` is also used in many web apps.  AFAIK, `request` doesn't officially support browser usage, so there's risk of things not working for web apps.  Adding `request` also brings in 48 new dependencies, which will bloat the size of the browser bundle significantly. 

Proxy support is something that would only be needed in Node.js, not web apps (since the browser is responsible for proxy support).  So perhaps there's a way to refactor the [HTTP resolver](https://github.com/APIDevTools/json-schema-ref-parser/blob/master/lib/resolvers/http.js) so that the proxy-related code is only imported by Node.js and not by Browserify.

**Comment by dowlingw** [comment]
Yeah that's fair.

I did note that `withCredentials` isn't explicitly supported by `request` during development, though didn't join the dots to it not supporting browser use entirely.

Will have a noodle over this and see if I can come back with something better, cheers :)

**Comment by dowlingw** [comment]
Closing as I haven't been able to come back to this, sorry! :(

**Pull request closed without merging**
