### PR TITLE
Convert relative refs when resolving an external schema

### PR DESCRIPTION
**Pull request by karlvr**
Possibly corrects #200.

This however causes tests to fail as they’re not expecting the references to be resolved. I’m not sure yet how to fix the tests. I thought I’d wait to see if the fix is valid!

I'd love some feedback on this to progress it or change it!

### CODE REVIEW

**Comment by philsturgeon** [comment]
@karlvr hey I've poked a few people about trying to get a review, and hopefully it'll be more successful than when I tried 14 months ago.

**Comment by mweber03** [comment]
Bump

**Comment by Borduhh** [comment]
Any update on this? We'd be happy to look at the tests and change them if needed but are not maintainers on the project.

**Comment by danielfcollier** [comment]
Hi @karlvr, can you help to add some tests?

I've updated your contributions and added a basic test setup here: https://github.com/danielfcollier/json-schema-ref-parser/tree/ISSUE-200 (I've added it on top of ISSUE-283 due to compatibility with tests on Windows).

Testing, for now, seems ok, but I think it is better to add tests to make the PR keep tracking of the expected feature.

**Comment by danielfcollier** [comment]
Hi there, 

can someone help to write tests for this feature? 

I've tested with `npm run coverage:node` @karlvr branch, and the tests are not passing, is that right? Please, correct with I'm wrong.

There is a starting point  for the tests here: https://github.com/APIDevTools/json-schema-ref-parser/commit/e1217174563c57cd81bc06259cf665606295ebf9

(I've added a branch with changes from this PR on top of some changes done for ISSUE-283 for tests on Windows.)

**Comment by philsturgeon** [comment]
We'd need the conflicts fixed, but seems like nobody is around to review this other than me. Gulp.

**Comment by mikethecalamity** [comment]
Bump? (I guess it's that time of year)

**Comment by philsturgeon** [comment]
@jonluca tagging you I’m if you’ve got time to have a look here. I’m not involved anymore.

**Comment by jonluca** [comment]
I'm open to a PR here but would need to update it to pass the tests and to use the new typescript repo. Closing this for now, feel free to open a new one

**Comment by mikethecalamity** [comment]
Where's the new repo?

**Comment by jonluca** [comment]
It's this repo - all the code was migrated to TS ~8 months ago

**Comment by mikethecalamity** [comment]
So I put the updates into a new PR: https://github.com/APIDevTools/json-schema-ref-parser/pull/322

But I have no idea if it's right, I've never used typescript before.

**Pull request closed without merging**
