### PR TITLE
handle id dereference

### LINKED ISSUE #136: Internal $id reference not derefernced
STR:
1. Create file `schema.json`
```json
{
  "$schema": "http://json-schema.org/draft-07/schema#",

  "definitions": {
    "address": {
      "$id": "#address",
      "type": "object",
      "properties": {
        "street_address": { "type": "string" },
        "city":           { "type": "string" },
        "state":          { "type": "string" }
      },
      "required": ["street_address", "city", "state"]
    }
  },

  "type": "object",

  "properties": {
    "billing_address": { "$ref": "#address" },
    "shipping_address": { "$ref": "#address" }
  }
}
```
this actually example from https://json-schema.org/understanding-json-schema/structuring.html#using-id-with-ref

2. `npm i json-schema-ref-parser`
3. `node -e "(async () => { console.log(JSON.stringify(await require('json-schema-ref-parser').dereference(require('./schema.json')), null, 2))})()"`

Actual result:
```json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "address": {
      "$id": "#address",
      "type": "object",
      "properties": {
        "street_address": {
          "type": "string"
        },
        "city": {
          "type": "string"
        },
        "state": {
          "type": "string"
        }
      },
      "required": [
        "street_address",
        "city",
        "state"
      ]
    }
  },
  "type": "object",
  "properties": {
    "billing_address": {
      "$ref": "#address"
    },
    "shipping_address": {
      "$ref": "#address"
    }
  }
}
```

Expected result:
`properties.billing_address` and `properties.shipping_address` are dereferenced

### PR DESCRIPTION
**Pull request by mathieudutour**
fix #136

### CODE REVIEW

**Comment by transitive-bullshit** [comment]
This is a really solid PR -- great work @mathieudutour. Would also love to see this merged.

**Comment by jrnail23** [comment]
Are there plans to merge this?  I'm impacted by this issue and would also love to see it merged.

**Comment by philsturgeon** [comment]
$id/$ref is a pretty wild topic so we'd need a lot more input from the JSON Schema experts, and that one already has a pretty solid roadmap for 2019-09 support in #145. 

Maybe we should focus our efforts on that instead?

**Comment by unlimitechcloud** [comment]
Hi, im needing this too, any ETA?

**Comment by philsturgeon** [comment]
@unlimitechcloud could you try this PR out and see if it works for your use cases?

**Comment by philsturgeon** [comment]
Conflicts and original branch has gone. This is being handled in https://github.com/APIDevTools/json-schema-reader

**Pull request closed without merging**
