### PR TITLE
Issue 283

### PR DESCRIPTION
**Pull request by danielfcollier**
Issue: https://github.com/APIDevTools/json-schema-ref-parser/issues/283

The problem has been solved by working only with absolute paths on Windows.

Currently, there are 252 passing tests on Windows and 254 passing tests on Linux (probably MacOS too).

Some tests at:
- test/specs/invalid/invalid.spec.js
- test/specs/missing-pointers/missing-pointers.spec.js
- test/specs/object-source/object-source.spec.js

have been fixed to work on any OS or skipped due to conflicts on Windows (error messages that still keeps the `\\` from Windows.) 

Three tests at `test/specs/http.spec.js` have been skipped and it might require opening another issue to investigate further.

### CODE REVIEW

**Review by philsturgeon — APPROVED** [review]

**Comment by danielfcollier** [comment]
I will see why the CI has broken.

**Comment by danielfcollier** [comment]
@philsturgeon, please, run the CI again - I'm still trying to understand if the changes are enough to pass the tests pipeline.

I'm trying to run the CI locally to check first here if it is going to pass. But, it is my first with GitHub Actions (I've just run GitLab Runner), so this is another science...

**Comment by philsturgeon** [comment]
Nearly there @danielfcollier, sorry this is a bit abourious. I'll add you as a collaborator so it will let the checks run qithout manual approval.

**Comment by danielfcollier** [comment]
Hey @philsturgeon, thanks! I will see, looking forward to solve more issues.

**Pull request merged**
