### PR TITLE
fix: add `JSONSchema7` types, `resolve` option index signature & missing `JSONSchema` return type in resolver options `read`

### LINKED ISSUE #224: Inconsistencies in type definitions
Hi.

I encountered a few inconsistencies in included type definitions:

- they don't support `JSONSchema7`, whereas the tool is draft agnostic
- the `resolve` Options key doesn't pass strict mode checks, because its index signature is not compatible with the defined keys
- the `ResolverOptions` interface has its `read` function signature return type union missing `JSONSchema`

I'll be submitting a PR in a few minutes!

### PR DESCRIPTION
**Pull request by medfreeman**
Fixes #224

### CODE REVIEW

**Comment by jasonterando** [comment]
Hi, any traction on this?  I'm trying to use this with the output from ts-json-schema-generator, and that outputs JSONSchema7

**Review by philsturgeon — APPROVED** [review]

**Review by philsturgeon — APPROVED** [review]

**Comment by medfreeman** [comment]
shall i do something?

**Comment by philsturgeon** [comment]
I'm not sure what the hell is going on here @medfreeman sorry! I've been trying to get tests running for a little while but its not going anywhere.

**Comment by philsturgeon** [comment]
Aha! Got it. When https://github.com/APIDevTools/json-schema-ref-parser/pull/233 is merged please update your branch.

**Review by Ayaz410808 — COMMENTED** [review]
Ip

**Pull request merged**
