### PR TITLE
Esmification

### PR DESCRIPTION
**Pull request by aerialist7**
Hi Team,
I've prepare the ESM version of the library.
Can you please review the changes and merge them if OK?

### CODE REVIEW

**Comment by aerialist7** [comment]
Hi @P0lip, hi @philsturgeon

I've fixed the ESLint, but seems tests will fail because of `type: "module"`.

Can you consult me, how to correctly update project config to enable es-modules for test environment?

**Comment by philsturgeon** [comment]
@aerialist7 I understand this situation a lot better now, and I see that there's a way to go ahead with this pull request if you're still interested! 

https://dev.to/bcoe/esm-doesn-t-need-to-break-the-ecosystem-4p8b

They talk about conditional imports: 

```
  {
    "exports": {
      ".": {
        "import": "./index.mjs",
        "require": "./index.cjs"
      },
      "./helpers": {
        "import": "./helpers/helpers.mjs",
        "require": "./helpers/index.js"
      }
    }
  }
```

Can we set that up so things will continue to work for CJS and ESM?

Then we'll avoid the problems discussed in the node-fetch issue.

**Comment by aerialist7** [comment]
Hi @philsturgeon, thank you for your respond. 
I think we can, but we need to configure build to CJS and ESM together.

**Comment by philsturgeon** [comment]
I'll admit I'm not caught up with all this, but I have blundered my way through it with help on other projects. 

https://github.com/stoplightio/spectral-owasp-ruleset/blob/main/package.json

We got that repo building from TS to CJS and ESM so perhaps something can be nicked from there. 

Do you think you could take a swing at it?

**Comment by philsturgeon** [comment]
I've just merged two large changes which will have caused some conflicts here, sorry about that. I'm done merging big changes now though so you've got a clear runway to land this change.

**Comment by deepakthankachan** [comment]
any updates on this? cheers

**Comment by philsturgeon** [comment]
@deepakthankachan you know if this PR has updates because it will show them. Currently there are conflicts and failing tests so we're just waiting for that to get fixed.

**Comment by wparad** [comment]
The best way to proceed with this is first add in building the library with a tool that can output both esm and cjs and then do the esm changes if we want. There shouldn't really be a reason we need to introduce esm though, since esm can already import cjs files which the library currently is. If we see the value in converting to esm in the long run then making those changes piecemeal in follow up PRs is the best way to go.

**Comment by philsturgeon** [comment]
@acunniffe any chance you can pick this PR up and get it over the line?

**Comment by philsturgeon** [comment]
I've made progress over here if anyone is interested in continuing this effort.

**Comment by philsturgeon** [comment]
More progress is being made in #288 and this one isn't being worked on so I'll close this for that.

**Pull request closed without merging**
