### PR TITLE
Upgrade js-yaml

### PR DESCRIPTION
**Pull request by wparad**

### CODE REVIEW

**Comment by philsturgeon** [comment]
Sorry I'm trying to figure out the problems with GitHub Actions, I might have just done it, but we've got some conflicts now. Could you have a look?

**Comment by wparad** [comment]
@philsturgeon, the `CI-CD.yml` was missing a `pull_request:` I've fixed, but I need someone to allow running them before they'll trigger.

**Review by philsturgeon — APPROVED** [review]

**Comment by philsturgeon** [comment]
Thank you! I just landed on that same conclusion myself #238 🤣  Will merge yours as soon as its done.

**Comment by wparad** [comment]
yikes, `npm run test` worked on my machine ;)

```sh
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.2 LTS"
```

**Comment by wparad** [comment]
Are secrets available in PR jobs?

```yml
      - name: Run tests
        run: npm run coverage:browser
        env:
          SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
          SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
```

**Comment by wparad** [comment]
Is this the problem:
image

**Review by philsturgeon — APPROVED** [review]

**Comment by philsturgeon** [comment]
Got it! I dont know what's been going on around here but there's a few problems that need fixing. I'll get things sorted out when I dont feel like I'm dying! :D Thanks for your patience.

**Pull request merged**
